[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install --no-cache-dir -r requirements.txt",
    "python3 -m pip install --no-cache-dir -r requirements-dev.txt"
]

[start]
cmd = "python3 agents/crewai/crew_agent_server_with_guard_rails.py"

